name: Continuous integration

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Build
        run: cargo build --release

      - name: Test
        run: cargo test --release

      - name: Lint
        run: cargo clippy --release -- -D warnings

      - name: Check formatting
        run: cargo +nightly fmt --check
